version: "2"

services:
  jmaster:
    build:
      context: master/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_OPTS
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size:  "200m"
        max-file: "3"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $HOME/.ssh:/var/jenkins_home/.ssh
      - $HOME/jenkins-backup/jobs:/var/jenkins_home/jobs
      - $HOME/jenkins-backup/userContent:/var/jenkins_home/userContent
      - /etc/localtime:/etc/localtime

  jslave:
    build:
      context: slave/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size:  "200m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - $HOME/jenkins-backup/slave/gradle:/root/.gradle
      - $HOME/jenkins-backup/workspace:/root/workspace
      - /etc/localtime:/etc/localtime

  registry:
    image: registry:2.4.0
    ports:
      - 5000:5000
    volumes:
      - $HOME/jenkins-backup/registry:/var/lib/registry
      - /etc/localtime:/etc/localtime

  registry-web:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8081:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_MODE_BROWSE_ONLY=true
    volumes:
      - /etc/localtime:/etc/localtime