version: "2"

services:
  jmaster:
    build:
      context: master/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_OPTS
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $HOME/.ssh:/var/jenkins_home/.ssh
      - $HOME/jenkins-backup/jobs:/var/jenkins_home/jobs

  jslave:
    build:
      context: slave/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - $HOME/jenkins-backup/slave/gradle:/root/.gradle

  registry:
    image: registry:2.4.0
    ports:
      - 5000:5000
    volumes:
      - $HOME/jenkins-backup/registry:/var/lib/registry

  registry-web:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8081:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_MODE_BROWSE_ONLY=true
